# -*- coding: utf-8 -*-
"""machine_learning_01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KFx2kY8GLG_4Cf0-qMOuOUgR2lItxo9I

**Aula 01**

A ideia desse primeiro projeto é usar o machine learning para diferenciar dois animais com características diferentes: um porco e um cachorro.
"""

