# -*- coding: utf-8 -*-
"""machine_learning_01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KFx2kY8GLG_4Cf0-qMOuOUgR2lItxo9I

**Aula 01**

A ideia desse primeiro projeto é usar o machine learning para diferenciar dois animais com características diferentes: um porco e um cachorro.
"""

#Será usada classificação binária: 0 = Cachorro e 1 = Porco (Classificação)
#Usaremos 3 caractéristica: (Features)

#  0 = Pelo Curto e 1 = Pelo Longo
#  0 = Perna Longa e 1 = Perna Curta
#  0 = não faz 'Au Au' e 1 = faz 'Au au'